export const AUTH_VALIDATE_TOKEN = 'AUTH_VALIDATE_TOKEN'
export const AUTH_VALIDATE_TOKEN_SUCCESS = 'AUTH_VALIDATE_TOKEN_SUCCESS'
export const AUTH_VALIDATE_TOKEN_ERROR = 'AUTH_VALIDATE_TOKEN_ERROR'

export const AUTH_RENEW_TOKEN = 'AUTH_RENEW_TOKEN'
export const AUTH_RENEW_TOKEN_SUCCESS = 'AUTH_RENEW_TOKEN_SUCCESS'
export const AUTH_RENEW_TOKEN_ERROR = 'AUTH_RENEW_TOKEN_ERROR'

export const AUTH_FETCH_TOKEN = 'AUTH_FETCH_TOKEN'
export const AUTH_FETCH_TOKEN_SUCCESS = 'AUTH_FETCH_TOKEN_SUCCESS'
export const AUTH_FETCH_TOKEN_ERROR = 'AUTH_FETCH_TOKEN_ERROR'

export const AUTH_FETCH_USER = 'AUTH_FETCH_USER'
export const AUTH_LOGIN = 'AUTH_LOGIN'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

